# Generated by Django 4.2.2 on 2023-06-17 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.RunSQL(
            """
        INSERT INTO store_collection(title)
        values ("collection1")
                                    """,
            """
DELETE FROM store_collection
where title='collection1'
                                    """,
        )
    ]
